local_backend: true
backend:
  name: git-gateway
  branch: master
media_folder: 'src/uploads'
public_folder: '/uploads'

navigation: &NAVIGATION
  label: 'Navigation'
  name: 'eleventyNavigation'
  widget: 'object'
  collasped: true
  fields:
    - { label: 'Key', name: 'key', widget: 'string', required: false }
    - { label: 'Parent', name: 'parent', widget: 'string', required: false }
    - { label: 'Order', name: 'order', widget: 'number', required: false }
    - { label: 'Excerpt', name: 'excerpt', widget: 'string', required: false }

blocks: &BLOCKS
  label: 'Blocks'
  name: 'blocks'
  widget: 'list'
  types:
    - label: 'Text'
      name: 'text'
      widget: object
      fields:
        - { label: 'Title', name: 'title', widget: 'string' }
        - { label: 'Content', name: 'content', widget: 'markdown' }
    - label: 'Image'
      name: 'image'
      widget: 'object'
      fields:
        - { label: 'Image', name: 'image', widget: 'image' }
        - { label: 'Alt', name: 'alt', widget: 'string', required: false }

collections:
  - label: 'Pages'
    name: 'pages'
    folder: 'src'
    identifier_field: 'title'
    create: true
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    extension: 'md'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'layouts/page.njk' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - *BLOCKS
      - *NAVIGATION